site_name: Zelda 64 Custom Music Wiki
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: en
  palette:

    # light mode, automatically assigned by default to users with light OS theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode
      primary: indigo
      accent: deep purple

    # dark mode, automatically assigned by default to users with dark OS theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode
      primary: indigo
      accent: deep purple

# extra:
  # social:
    # - icon: fontawesome/brands/discord
      # link: https://discord.gg/ootrandomizer
      # name: Ocarina of Time Randomizer Discord
    # - icon: fontawesome/brands/discord
      # link: https://discord.gg/7jBRhhJ
      # name: Majora's Mask Randomizer Discord
    # - icon: fontawesome/brands/discord
      # link: https://discord.gg/4QdtPBP6wf
      # name: OOTMM Randomizer Discord

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page Tree
nav:
  - Home: index.md
  - Getting Started:
    - Requirements: requirements.md
  - Basic:
    - a: a.md
  - Advanced:
    - Tuning: tuning.md

# copyright information
copyright: |
  Copyright &copy; 2024 <a href="https://github.com/bombchus" target="_blank" rel="noopener">Bombchus</a>